name = "mrg-caixas-termicas"
compatibility_date = "2024-10-24"
pages_build_output_dir = "out"

[env.production]
name = "mrg-caixas-termicas"
route = "mrgcaixastermicas.com.br/*"
zone_name = "mrgcaixastermicas.com.br"

[env.production.vars]
NODE_VERSION = "18"
NEXT_PUBLIC_SITE_URL = "https://mrgcaixastermicas.com.br"